name: VPN Sync
on:
  workflow_dispatch:

jobs:
  vpn-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync VPN configurations
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPN_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo wg-sync-configs.sh
          echo "VPN configurations synchronized!"

    - name: Send Telegram notification
      uses: appleboy/telegram-action@v1.0.0
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          🔄 VPN configurations synchronized!
          🖥️ Server: ${{ secrets.VPN_SERVER_IP }}
          ⏰ Time: ${{ steps.date.outputs.date }}